"""
AI Client for interfacing with language models
"""

import asyncio
import logging
from typing import Dict, List, Any, Optional
import openai
from ..config import AI_DM_CONFIG

logger = logging.getLogger(__name__)


class AIClient:
    """Client for AI language model interactions"""
    
    def __init__(self):
        self.client = None
        self.model = AI_DM_CONFIG["model"]
        self.temperature = AI_DM_CONFIG["temperature"]
        self.max_tokens = AI_DM_CONFIG["max_tokens"]
        
        # Initialize OpenAI client
        if AI_DM_CONFIG["openai_api_key"]:
            openai.api_key = AI_DM_CONFIG["openai_api_key"]
            self.client = openai.OpenAI(api_key=AI_DM_CONFIG["openai_api_key"])
        
    async def generate_completion(self, prompt: str, max_tokens: Optional[int] = None,
                                temperature: Optional[float] = None) -> str:
        """Generate completion from AI model"""
        try:
            if not self.client:
                # Fallback for when no API key is provided
                return self._generate_fallback_response(prompt)
            
            response = await asyncio.to_thread(
                self.client.chat.completions.create,
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=max_tokens or self.max_tokens,
                temperature=temperature or self.temperature
            )
            
            return response.choices[0].message.content.strip()
            
        except Exception as e:
            logger.error(f"Error generating AI completion: {e}")
            return self._generate_fallback_response(prompt)
    
    def _generate_fallback_response(self, prompt: str) -> str:
        """Generate fallback response when AI is unavailable"""
        fallback_responses = {
            "generate": "This would be generated by AI based on the context.",
            "analyze": "Analysis would be provided by AI based on the given information.",
            "suggest": "AI would provide suggestions based on the context.",
            "explain": "AI would provide an explanation of the situation.",
            "create": "AI would create content based on the parameters."
        }
        
        prompt_lower = prompt.lower()
        for key, response in fallback_responses.items():
            if key in prompt_lower:
                return response
        
        return "AI response would be generated based on the prompt context."


class CoherenceAnalyzer:
    """Analyzes narrative coherence"""
    
    def __init__(self):
        pass
    
    async def analyze_consistency(self, events: List[Any], plotlines: Dict[str, Any]) -> float:
        """Analyze consistency of narrative events"""
        # Simplified coherence analysis
        if not events:
            return 1.0
        
        # Check for timeline consistency
        timeline_score = 0.8
        
        # Check for character consistency
        character_score = 0.9
        
        # Check for world rule consistency
        world_score = 0.85
        
        return (timeline_score + character_score + world_score) / 3


class RandomTables:
    """Random generation tables"""
    
    def __init__(self):
        self.tables = {}
    
    async def initialize(self):
        """Initialize random tables"""
        self.tables = {
            "npc_names": ["Aelindra", "Borin", "Celes", "Daven", "Estra"],
            "locations": ["tavern", "shop", "temple", "tower", "cave"],
            "motivations": ["wealth", "power", "revenge", "love", "duty"]
        }
    
    def roll_table(self, table_name: str) -> str:
        """Roll on a random table"""
        import random
        table = self.tables.get(table_name, ["unknown"])
        return random.choice(table)