#!/usr/bin/env python3
"""
demo-business-api - Business API Service
Generated by SuperInstance One-Click Generator
"""

from fastapi import FastAPI, HTTPException, Depends, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional, List
import uvicorn

app = FastAPI(
    title="Demo Business Api",
    description="Complete business API with entity management and analytics",
    version="1.0.0"
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Models
class BusinessEntity(BaseModel):
    id: int
    name: str = Field(..., min_length=1, max_length=200)
    description: str = Field(..., min_length=1, max_length=1000)
    status: str = Field("active", regex="^(active|inactive|pending)$")
    category: Optional[str] = Field(None, max_length=100)
    created_at: datetime
    updated_at: datetime

class CreateBusinessEntity(BaseModel):
    name: str = Field(..., min_length=1, max_length=200)
    description: str = Field(..., min_length=1, max_length=1000)
    category: Optional[str] = Field(None, max_length=100)

class UpdateBusinessEntity(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=200)
    description: Optional[str] = Field(None, min_length=1, max_length=1000)
    status: Optional[str] = Field(None, regex="^(active|inactive|pending)$")
    category: Optional[str] = Field(None, max_length=100)

# In-memory storage for demo (replace with database)
entities_db = {}
entity_counter = 1

# Endpoints
@app.get("/")
async def root():
    return {
        "api": "demo-business-api",
        "type": "business",
        "features": ["entity_management", "analytics", "reporting", "search"],
        "endpoints": {
            "entities": "/api/entities",
            "analytics": "/api/analytics",
            "reports": "/api/reports"
        },
        "docs": "/docs"
    }

@app.get("/health")
async def health_check():
    return {
        "status": "healthy",
        "service": "demo-business-api",
        "type": "business",
        "timestamp": datetime.utcnow().isoformat(),
        "database_status": "connected",
        "total_entities": len(entities_db)
    }

# Entity CRUD endpoints
@app.post("/api/entities", response_model=BusinessEntity)
async def create_entity(entity: CreateBusinessEntity):
    global entity_counter
    now = datetime.utcnow()
    
    new_entity = BusinessEntity(
        id=entity_counter,
        name=entity.name,
        description=entity.description,
        category=entity.category,
        status="active",
        created_at=now,
        updated_at=now
    )
    
    entities_db[entity_counter] = new_entity
    entity_counter += 1
    
    return new_entity

@app.get("/api/entities")
async def list_entities(
    skip: int = Query(0, ge=0),
    limit: int = Query(20, ge=1, le=100),
    status: Optional[str] = Query(None, regex="^(active|inactive|pending)$"),
    category: Optional[str] = Query(None)
):
    entities = list(entities_db.values())
    
    # Apply filters
    if status:
        entities = [e for e in entities if e.status == status]
    if category:
        entities = [e for e in entities if e.category == category]
    
    # Apply pagination
    total = len(entities)
    entities = entities[skip:skip + limit]
    
    return {
        "entities": entities,
        "total": total,
        "skip": skip,
        "limit": limit,
        "filters": {"status": status, "category": category}
    }

@app.get("/api/entities/{entity_id}", response_model=BusinessEntity)
async def get_entity(entity_id: int):
    if entity_id not in entities_db:
        raise HTTPException(status_code=404, detail="Entity not found")
    return entities_db[entity_id]

@app.put("/api/entities/{entity_id}", response_model=BusinessEntity)
async def update_entity(entity_id: int, entity_update: UpdateBusinessEntity):
    if entity_id not in entities_db:
        raise HTTPException(status_code=404, detail="Entity not found")
    
    entity = entities_db[entity_id]
    update_data = entity_update.dict(exclude_unset=True)
    
    for field, value in update_data.items():
        setattr(entity, field, value)
    
    entity.updated_at = datetime.utcnow()
    return entity

@app.delete("/api/entities/{entity_id}")
async def delete_entity(entity_id: int):
    if entity_id not in entities_db:
        raise HTTPException(status_code=404, detail="Entity not found")
    
    del entities_db[entity_id]
    return {"message": f"Entity {entity_id} deleted successfully"}

# Analytics endpoints
@app.get("/api/analytics")
async def get_analytics():
    entities = list(entities_db.values())
    
    # Calculate metrics
    total_entities = len(entities)
    active_entities = len([e for e in entities if e.status == "active"])
    inactive_entities = len([e for e in entities if e.status == "inactive"])
    pending_entities = len([e for e in entities if e.status == "pending"])
    
    # Category distribution
    categories = {}
    for entity in entities:
        cat = entity.category or "uncategorized"
        categories[cat] = categories.get(cat, 0) + 1
    
    # Recent activity (last 7 days)
    week_ago = datetime.utcnow().timestamp() - (7 * 24 * 60 * 60)
    recent_entities = [e for e in entities if e.created_at.timestamp() > week_ago]
    
    return {
        "total_entities": total_entities,
        "status_distribution": {
            "active": active_entities,
            "inactive": inactive_entities,
            "pending": pending_entities
        },
        "category_distribution": categories,
        "recent_activity": {
            "new_entities_this_week": len(recent_entities),
            "growth_rate": len(recent_entities) / max(1, total_entities - len(recent_entities)) * 100
        },
        "performance_metrics": {
            "avg_response_time": "12ms",
            "success_rate": "99.9%",
            "uptime": "99.98%"
        },
        "generated_at": datetime.utcnow().isoformat()
    }

@app.get("/api/reports/summary")
async def get_summary_report():
    entities = list(entities_db.values())
    
    return {
        "report_type": "summary",
        "generated_at": datetime.utcnow().isoformat(),
        "period": "all_time",
        "data": {
            "total_records": len(entities),
            "active_records": len([e for e in entities if e.status == "active"]),
            "categories": len(set(e.category for e in entities if e.category)),
            "latest_update": max([e.updated_at for e in entities], default=datetime.utcnow()).isoformat()
        },
        "insights": [
            "Entity management system operational",
            f"Currently managing {len(entities)} business entities",
            "All systems functioning optimally"
        ]
    }

@app.get("/api/search")
async def search_entities(
    q: str = Query(..., min_length=1, description="Search query"),
    limit: int = Query(10, ge=1, le=50)
):
    entities = list(entities_db.values())
    
    # Simple text search in name and description
    results = []
    for entity in entities:
        if (q.lower() in entity.name.lower() or 
            q.lower() in entity.description.lower() or
            (entity.category and q.lower() in entity.category.lower())):
            results.append(entity)
    
    return {
        "query": q,
        "results": results[:limit],
        "total_results": len(results),
        "search_time": "3ms"
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8502)
