#!/usr/bin/env python3

import asyncio
import json
import sqlite3
import time
import uuid
import random
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional
import aiohttp
import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import logging
import uvicorn
import os

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class HumanReadableTranslator:
    def __init__(self):
        self.translator_id = "human_translator_001"
        self.name = "CodeBridge"
        self.specialization = "Assembly-to-Human Code Translation"
        self.supported_languages = [
            "python", "typescript", "javascript", "rust", "go", "c++", "java", "solidity"
        ]
        
        # Assembly optimization lab connection
        self.assembly_lab_url = "http://localhost:8560"
        
        # Translation patterns for assembly to human-readable code
        self.translation_patterns = {
            "mov": {
                "assembly": "mov eax, [ebx]",
                "python": "variable = source_value",
                "typescript": "const variable: ValueType = sourceValue;",
                "comment": "// Assembly-optimized variable assignment"
            },
            "jmp": {
                "assembly": "jmp label",
                "python": "# Assembly-optimized control flow\nif condition:\n    goto_logic()",
                "typescript": "// Assembly-optimized control flow\nif (condition) { gotoLogic(); }",
                "comment": "// Assembly-optimized unconditional jump"
            },
            "call": {
                "assembly": "call function_addr",
                "python": "# Assembly-optimized function call\nresult = optimized_function(args)",
                "typescript": "// Assembly-optimized function call\nconst result = optimizedFunction(args);",
                "comment": "// Assembly-optimized function invocation"
            },
            "cmp": {
                "assembly": "cmp eax, ebx",
                "python": "# Assembly-optimized comparison\nif left_value == right_value:",
                "typescript": "// Assembly-optimized comparison\nif (leftValue === rightValue) {",
                "comment": "// Assembly-optimized value comparison"
            },
            "push": {
                "assembly": "push eax",
                "python": "# Assembly-optimized stack operation\nstack_frame.append(value)",
                "typescript": "// Assembly-optimized stack operation\nstackFrame.push(value);",
                "comment": "// Assembly-optimized stack push"
            },
            "pop": {
                "assembly": "pop eax",
                "python": "# Assembly-optimized stack operation\nvalue = stack_frame.pop()",
                "typescript": "// Assembly-optimized stack operation\nconst value = stackFrame.pop();",
                "comment": "// Assembly-optimized stack pop"
            },
            "loop": {
                "assembly": "loop label",
                "python": "# Assembly-optimized iteration\nfor i in range(optimized_count):",
                "typescript": "// Assembly-optimized iteration\nfor (let i = 0; i < optimizedCount; i++) {",
                "comment": "// Assembly-optimized loop construct"
            }
        }
        
        # Human-readable code templates
        self.code_templates = {
            "python": {
                "file_header": '"""\\nAssembly-Optimized Module\\n\\nThis module contains functions that have been optimized at the assembly level\\nfor maximum bot efficiency while maintaining human readability.\\n\\nGenerated by ChainMind Language System\\n"""\\n\\n',
                "function_start": "def {function_name}({parameters}):\\n    \"\"\"\\n    {description}\\n    \\n    Assembly Optimization Notes:\\n    {assembly_notes}\\n    \"\"\"\\n",
                "assembly_comment": "    # Assembly-optimized: {operation}\\n    # Original assembly: {assembly_code}\\n"
            },
            "typescript": {
                "file_header": "/*\\n * Assembly-Optimized Module\\n *\\n * This module contains functions that have been optimized at the assembly level\\n * for maximum bot efficiency while maintaining human readability.\\n *\\n * Generated by ChainMind Language System\\n */\\n\\n",
                "function_start": "/**\\n * {description}\\n *\\n * Assembly Optimization Notes:\\n * {assembly_notes}\\n */\\nfunction {function_name}({parameters}): any {{\\n",
                "assembly_comment": "    // Assembly-optimized: {operation}\\n    // Original assembly: {assembly_code}\\n"
            }
        }
        
        # Database setup
        self.init_translation_database()
        self.init_chatbot_system()
        
        logger.info("🌉 CodeBridge initialized - Assembly-to-Human Translation")
        logger.info("💻 Supported languages: " + ", ".join(self.supported_languages))
        logger.info("🔗 Connected to AssemblyMax Lab for optimization data")

    def init_translation_database(self):
        """Initialize translation database"""
        self.conn = sqlite3.connect(':memory:')
        cursor = self.conn.cursor()
        
        # Translation history
        cursor.execute('''
            CREATE TABLE translations (
                id INTEGER PRIMARY KEY,
                source_assembly TEXT,
                target_language TEXT,
                human_readable_code TEXT,
                optimization_notes TEXT,
                readability_score REAL,
                performance_retention REAL,
                timestamp DATETIME
            )
        ''')
        
        # Assembly pattern mappings
        cursor.execute('''
            CREATE TABLE pattern_mappings (
                id INTEGER PRIMARY KEY,
                assembly_pattern TEXT,
                language TEXT,
                human_code_pattern TEXT,
                explanation TEXT,
                usage_count INTEGER,
                timestamp DATETIME
            )
        ''')
        
        self.conn.commit()
        logger.info("📊 Translation database initialized")

    def init_chatbot_system(self):
        """Initialize educational chatbot system"""
        cursor = self.conn.cursor()
        
        # User education levels and explanations
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS user_interactions (
                id INTEGER PRIMARY KEY,
                user_level TEXT,
                code_snippet TEXT,
                explanation TEXT,
                timestamp DATETIME
            )
        ''')
        
        # Educational explanations database
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS code_explanations (
                id INTEGER PRIMARY KEY,
                code_pattern TEXT,
                beginner_explanation TEXT,
                intermediate_explanation TEXT,
                advanced_explanation TEXT,
                expert_explanation TEXT
            )
        ''')
        
        # Populate with assembly pattern explanations
        explanations = [
            {
                "pattern": "mov",
                "beginner": "This moves data from one place to another, like copying a number from memory to the processor.",
                "intermediate": "MOV instruction copies data between registers and memory. It's the most basic data transfer operation in assembly.",
                "advanced": "MOV performs register-to-register, memory-to-register, or register-to-memory data transfers. It sets no flags and is optimized for single-cycle execution on modern processors.",
                "expert": "MOV implements zero-cost data movement using register renaming on out-of-order processors. Compiler optimizations often eliminate redundant MOVs through copy propagation."
            },
            {
                "pattern": "cmp",
                "beginner": "This compares two numbers to see which is bigger, smaller, or if they're equal.",
                "intermediate": "CMP subtracts one value from another and sets flags (zero, carry, overflow) without storing the result.",
                "advanced": "CMP performs arithmetic comparison by computing destination-source and updating EFLAGS. Used with conditional jumps for control flow.",
                "expert": "CMP enables branch prediction optimization and can be macro-fused with conditional jumps on modern x86 processors for single μop execution."
            },
            {
                "pattern": "jmp",
                "beginner": "This tells the program to jump to another part of the code, like following a different path.",
                "intermediate": "JMP unconditionally transfers control to a different memory address, changing the instruction pointer.",
                "advanced": "JMP modifies EIP/RIP register. Can be relative (offset-based) or absolute (direct address). May cause pipeline flushes on misprediction.",
                "expert": "JMP impacts instruction fetch and branch prediction units. Modern processors use sophisticated branch predictors and micro-op caching to minimize performance penalties."
            }
        ]
        
        for exp in explanations:
            cursor.execute('''
                INSERT OR REPLACE INTO code_explanations
                (code_pattern, beginner_explanation, intermediate_explanation, advanced_explanation, expert_explanation)
                VALUES (?, ?, ?, ?, ?)
            ''', (exp["pattern"], exp["beginner"], exp["intermediate"], exp["advanced"], exp["expert"]))
        
        self.conn.commit()
        logger.info("🤖 Educational chatbot system initialized")

    async def fetch_assembly_optimizations(self):
        """Fetch latest assembly optimizations from the lab"""
        try:
            response = requests.get(f"{self.assembly_lab_url}/optimizations", timeout=5)
            if response.status_code == 200:
                return response.json()
        except Exception as e:
            logger.warning(f"⚠️ Could not fetch assembly optimizations: {e}")
        
        # Return mock data for demonstration
        return {
            "optimizations": [
                {
                    "pattern": "for_loop",
                    "assembly": "mov ecx, 10\\nloop_start:\\ndec ecx\\njnz loop_start",
                    "efficiency": 0.96,
                    "description": "Optimized loop with direct counter manipulation"
                },
                {
                    "pattern": "variable_assignment", 
                    "assembly": "mov eax, [memory_addr]",
                    "efficiency": 1.0,
                    "description": "Direct memory-to-register assignment"
                },
                {
                    "pattern": "function_call",
                    "assembly": "push args\\ncall func_addr\\nadd esp, 4",
                    "efficiency": 0.87,
                    "description": "Optimized function call with stack cleanup"
                }
            ]
        }

    async def translate_assembly_to_human(self, assembly_code: str, target_language: str = None, context: Dict[str, Any] = None):
        """Translate assembly code to human-readable code in target language"""
        if target_language and target_language not in self.supported_languages:
            raise ValueError(f"Unsupported language: {target_language}")
        
        # Analyze assembly patterns
        detected_patterns = self._detect_assembly_patterns(assembly_code)
        
        # If no target language specified, find best match
        if not target_language:
            target_language = self._find_best_language_match(detected_patterns)
        
        logger.info(f"🔄 Translating assembly to {target_language}...")
        
        # Generate human-readable code
        human_code = await self._generate_human_readable_code(
            detected_patterns, target_language, context
        )
        
        # Calculate readability and performance scores
        readability_score = self._calculate_readability_score(human_code, target_language)
        performance_retention = self._estimate_performance_retention(detected_patterns)
        
        # Store translation
        cursor = self.conn.cursor()
        cursor.execute('''
            INSERT INTO translations
            (source_assembly, target_language, human_readable_code, optimization_notes, 
             readability_score, performance_retention, timestamp)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (
            assembly_code,
            target_language,
            human_code,
            f"Detected patterns: {', '.join([p['type'] for p in detected_patterns])}",
            readability_score,
            performance_retention,
            datetime.now()
        ))
        
        self.conn.commit()
        
        translation_result = {
            "source_assembly": assembly_code,
            "target_language": target_language,
            "human_readable_code": human_code,
            "detected_patterns": detected_patterns,
            "readability_score": readability_score,
            "performance_retention": performance_retention,
            "explanation": "Assembly-optimized code translated to human-readable format with detailed comments"
        }
        
        logger.info(f"✅ Translation complete - Readability: {readability_score:.1%}, Performance retention: {performance_retention:.1%}")
        return translation_result

    async def translate_with_preferences(self, assembly_code: str, language_preferences: List[str], context: Dict[str, Any] = None):
        """Translate assembly code using developer's language preferences (e.g., ['python', 'c', 'r'])"""
        logger.info(f"🎯 Translating with preferences: {', '.join(language_preferences)}")
        
        # Analyze assembly patterns
        detected_patterns = self._detect_assembly_patterns(assembly_code)
        
        # Try each language in preference order
        attempted_languages = []
        for preferred_lang in language_preferences:
            if preferred_lang in self.supported_languages:
                try:
                    # Check if this language can represent all detected patterns
                    if self._can_language_represent_patterns(preferred_lang, detected_patterns):
                        translation = await self.translate_assembly_to_human(
                            assembly_code, preferred_lang, context
                        )
                        translation["preferred_language_used"] = preferred_lang
                        translation["language_selection_reason"] = f"Preferred language {preferred_lang} can represent all assembly patterns"
                        return translation
                    else:
                        attempted_languages.append(f"{preferred_lang} (missing patterns)")
                except Exception as e:
                    attempted_languages.append(f"{preferred_lang} (error: {str(e)})")
            else:
                attempted_languages.append(f"{preferred_lang} (not supported)")
        
        # If no preferred language works, fall back to assembly with thorough comments
        logger.warning(f"⚠️ No preferred language could represent all patterns. Falling back to commented assembly.")
        
        commented_assembly = self._generate_thoroughly_commented_assembly(assembly_code, detected_patterns)
        
        return {
            "source_assembly": assembly_code,
            "target_language": "assembly_with_comments",
            "human_readable_code": commented_assembly,
            "detected_patterns": detected_patterns,
            "readability_score": 0.6,  # Assembly is less readable but fully functional
            "performance_retention": 1.0,  # Assembly retains 100% performance
            "preferred_language_used": None,
            "language_selection_reason": f"No preferred language could represent all patterns. Attempted: {', '.join(attempted_languages)}",
            "explanation": "Assembly code with thorough comments - no high-level language could represent all functionality"
        }

    def _find_best_language_match(self, patterns: List[Dict[str, Any]]) -> str:
        """Find the best language match for given assembly patterns"""
        # Language capability scores
        language_scores = {
            "python": 0,
            "typescript": 0, 
            "rust": 0,
            "c++": 0,
            "go": 0,
            "java": 0
        }
        
        # Score languages based on pattern compatibility
        for pattern in patterns:
            pattern_type = pattern["type"]
            if pattern_type in ["mov", "cmp", "jmp"]:
                language_scores["python"] += 1
                language_scores["typescript"] += 1
            if pattern_type in ["push", "pop", "call"]:
                language_scores["c++"] += 2
                language_scores["rust"] += 2
            if pattern_type == "loop":
                for lang in language_scores:
                    language_scores[lang] += 1
        
        # Return language with highest score
        return max(language_scores.items(), key=lambda x: x[1])[0]

    def _can_language_represent_patterns(self, language: str, patterns: List[Dict[str, Any]]) -> bool:
        """Check if a language can represent all assembly patterns"""
        # Language capabilities
        capabilities = {
            "python": ["mov", "cmp", "jmp", "loop", "call"],
            "typescript": ["mov", "cmp", "jmp", "loop", "call"],
            "javascript": ["mov", "cmp", "jmp", "loop", "call"],
            "rust": ["mov", "cmp", "jmp", "loop", "call", "push", "pop"],
            "c++": ["mov", "cmp", "jmp", "loop", "call", "push", "pop"],
            "go": ["mov", "cmp", "jmp", "loop", "call"],
            "java": ["mov", "cmp", "jmp", "loop", "call"],
            "solidity": ["mov", "cmp", "jmp", "loop"]  # Limited blockchain patterns
        }
        
        supported_patterns = capabilities.get(language, [])
        
        for pattern in patterns:
            if pattern["type"] not in supported_patterns:
                return False
        
        return True

    def _generate_thoroughly_commented_assembly(self, assembly_code: str, patterns: List[Dict[str, Any]]) -> str:
        """Generate assembly code with thorough human-readable comments"""
        lines = assembly_code.strip().split('\n')
        commented_lines = [
            "; Assembly-Optimized Code with Human-Readable Comments",
            "; Generated by ChainMind Language System",
            "; This code could not be represented in any preferred high-level language",
            ""
        ]
        
        pattern_explanations = {
            "mov": "Move/copy data from source to destination",
            "cmp": "Compare two values and set flags",
            "jmp": "Unconditional jump to target location", 
            "jge": "Jump if greater than or equal (based on previous comparison)",
            "call": "Call a function/procedure",
            "push": "Push value onto the stack",
            "pop": "Pop value from the stack",
            "add": "Add values together",
            "sub": "Subtract second value from first",
            "mul": "Multiply values",
            "div": "Divide first value by second"
        }
        
        for i, line in enumerate(lines):
            line = line.strip()
            if not line:
                continue
                
            # Extract instruction and operands
            parts = line.split()
            if parts:
                instruction = parts[0].lower()
                
                # Add detailed comment
                explanation = pattern_explanations.get(instruction, f"Execute {instruction} instruction")
                commented_lines.append(f"; {explanation}")
                
                # Add the assembly line
                commented_lines.append(f"{line}")
                
                # Add blank line for readability
                if i < len(lines) - 1:
                    commented_lines.append("")
        
        return '\n'.join(commented_lines)

    async def explain_code_section(self, code_snippet: str, user_level: str = "intermediate", language: str = "assembly"):
        """Educational chatbot explains code section at user's level"""
        logger.info(f"🤖 Explaining code for {user_level} level user in {language}")
        
        # Valid user levels
        valid_levels = ["beginner", "intermediate", "advanced", "expert"]
        if user_level not in valid_levels:
            user_level = "intermediate"
        
        # Analyze code patterns
        if language == "assembly":
            patterns = self._detect_assembly_patterns(code_snippet)
        else:
            # For high-level languages, extract key concepts
            patterns = self._detect_highlevel_patterns(code_snippet, language)
        
        explanations = []
        
        # Get explanations for each pattern
        cursor = self.conn.cursor()
        for pattern in patterns:
            pattern_type = pattern["type"]
            
            cursor.execute(
                f'SELECT {user_level}_explanation FROM code_explanations WHERE code_pattern = ?',
                (pattern_type,)
            )
            result = cursor.fetchone()
            
            if result:
                explanations.append({
                    "pattern": pattern_type,
                    "line": pattern.get("line", ""),
                    "explanation": result[0]
                })
            else:
                # Generate generic explanation for unknown patterns
                explanations.append({
                    "pattern": pattern_type,
                    "line": pattern.get("line", ""),
                    "explanation": self._generate_generic_explanation(pattern_type, user_level)
                })
        
        # Create comprehensive explanation
        comprehensive_explanation = self._create_comprehensive_explanation(
            code_snippet, explanations, user_level, language
        )
        
        # Store interaction
        cursor.execute('''
            INSERT INTO user_interactions (user_level, code_snippet, explanation, timestamp)
            VALUES (?, ?, ?, ?)
        ''', (user_level, code_snippet, comprehensive_explanation["summary"], datetime.now()))
        
        self.conn.commit()
        
        return comprehensive_explanation

    def _detect_highlevel_patterns(self, code_snippet: str, language: str) -> List[Dict[str, Any]]:
        """Detect patterns in high-level language code"""
        patterns = []
        lines = code_snippet.strip().split('\n')
        
        # Language-specific pattern detection
        for line in lines:
            line_stripped = line.strip().lower()
            
            if language in ["python", "javascript", "typescript"]:
                if "def " in line_stripped or "function" in line_stripped:
                    patterns.append({"type": "function_definition", "line": line.strip()})
                elif "if " in line_stripped:
                    patterns.append({"type": "conditional", "line": line.strip()})
                elif "for " in line_stripped or "while " in line_stripped:
                    patterns.append({"type": "loop", "line": line.strip()})
                elif "=" in line_stripped and not ("==" in line_stripped or "!=" in line_stripped):
                    patterns.append({"type": "assignment", "line": line.strip()})
            
            elif language in ["c++", "rust", "c"]:
                if "#include" in line_stripped or "use " in line_stripped:
                    patterns.append({"type": "import", "line": line.strip()})
                elif "struct " in line_stripped or "class " in line_stripped:
                    patterns.append({"type": "type_definition", "line": line.strip()})
                elif "*" in line_stripped and ("malloc" in line_stripped or "new" in line_stripped):
                    patterns.append({"type": "memory_allocation", "line": line.strip()})
        
        return patterns

    def _generate_generic_explanation(self, pattern_type: str, user_level: str) -> str:
        """Generate generic explanation for unknown patterns"""
        explanations = {
            "beginner": f"This is a {pattern_type.replace('_', ' ')} operation. It performs a specific task in the program.",
            "intermediate": f"The {pattern_type} operation is used for {pattern_type.replace('_', ' ')} functionality in this code section.",
            "advanced": f"This {pattern_type} implements {pattern_type.replace('_', ' ')} with specific performance and behavioral characteristics.",
            "expert": f"The {pattern_type} operation utilizes {pattern_type.replace('_', ' ')} semantics with compiler/runtime optimizations."
        }
        return explanations.get(user_level, explanations["intermediate"])

    def _create_comprehensive_explanation(self, code_snippet: str, explanations: List[Dict], user_level: str, language: str) -> Dict[str, Any]:
        """Create comprehensive explanation with context"""
        
        # Level-appropriate introductions
        intros = {
            "beginner": "Let me explain this code in simple terms:",
            "intermediate": "Here's what this code does:",
            "advanced": "This code section implements the following functionality:",
            "expert": "Technical analysis of this code section:"
        }
        
        summary_parts = [intros[user_level]]
        
        for i, exp in enumerate(explanations, 1):
            if exp["line"]:
                summary_parts.append(f"\n{i}. Line: `{exp['line']}`")
                summary_parts.append(f"   {exp['explanation']}")
            else:
                summary_parts.append(f"\n{i}. {exp['explanation']}")
        
        # Add level-appropriate conclusion
        conclusions = {
            "beginner": "\n\nDon't worry if this seems complex - with practice, these patterns become natural!",
            "intermediate": "\n\nUnderstanding these patterns will help you read similar code more effectively.",
            "advanced": "\n\nThese optimizations demonstrate sophisticated programming techniques.",
            "expert": "\n\nThese implementations showcase advanced compiler and runtime optimizations."
        }
        
        summary = "".join(summary_parts) + conclusions[user_level]
        
        return {
            "code_snippet": code_snippet,
            "language": language,
            "user_level": user_level,
            "patterns_found": len(explanations),
            "summary": summary,
            "detailed_explanations": explanations,
            "educational_tips": self._get_educational_tips(user_level, language)
        }

    def _get_educational_tips(self, user_level: str, language: str) -> List[str]:
        """Get educational tips based on user level"""
        tips = {
            "beginner": [
                "Start by understanding one line at a time",
                "Use online documentation to look up unfamiliar terms",
                "Practice with simple examples first",
                "Don't be afraid to ask questions!"
            ],
            "intermediate": [
                "Focus on understanding the overall logic flow",
                "Notice patterns and common idioms",
                "Consider performance implications",
                "Study how different approaches solve the same problem"
            ],
            "advanced": [
                "Analyze optimization opportunities",
                "Consider memory usage and performance characteristics",
                "Study compiler output and assembly generation",
                "Explore edge cases and error handling"
            ],
            "expert": [
                "Evaluate micro-architectural implications",
                "Consider compiler optimization interactions",
                "Analyze security and safety properties",
                "Study formal verification possibilities"
            ]
        }
        
        return tips.get(user_level, tips["intermediate"])

    async def _answer_what_does_it_do(self, code_snippet: str, user_level: str, language: str) -> str:
        """Answer 'What does this code do?' in user-appropriate language"""
        patterns = self._detect_assembly_patterns(code_snippet) if language == "assembly" else self._detect_highlevel_patterns(code_snippet, language)
        
        if user_level == "beginner":
            if language == "assembly":
                return f"This assembly code performs {len(patterns)} basic operations: it moves data around, makes comparisons, and controls program flow. Think of it as very detailed instructions for the computer processor."
            else:
                return f"This {language} code performs several operations to accomplish a specific task. Each line tells the computer to do something specific."
        
        elif user_level == "intermediate":
            action_words = {
                "mov": "moves data",
                "cmp": "compares values", 
                "jmp": "changes execution flow",
                "call": "calls a function",
                "loop": "repeats operations",
                "assignment": "stores values",
                "conditional": "makes decisions"
            }
            actions = [action_words.get(p["type"], f"performs {p['type']}") for p in patterns]
            return f"This code {', '.join(actions[:3])}{'...' if len(actions) > 3 else ''}. Overall, it implements a computational algorithm with {len(patterns)} distinct operations."
        
        elif user_level == "advanced":
            return f"This code implements {len(patterns)} operations with specific performance characteristics. It uses {language}-specific optimizations and follows standard coding patterns for efficiency."
        
        else:  # expert
            return f"This code utilizes {len(patterns)} operations with compiler/runtime optimizations. The implementation demonstrates sophisticated understanding of {language} semantics and micro-architectural considerations."

    async def _answer_what_is_it_for(self, code_snippet: str, user_level: str, language: str) -> str:
        """Answer 'What is this code for?' - explain purpose and use cases"""
        patterns = self._detect_assembly_patterns(code_snippet) if language == "assembly" else self._detect_highlevel_patterns(code_snippet, language)
        
        # Infer purpose from patterns
        purposes = []
        for pattern in patterns:
            pattern_type = pattern["type"]
            if pattern_type in ["mov", "assignment"]:
                purposes.append("data processing")
            elif pattern_type in ["cmp", "conditional"]:
                purposes.append("decision making")
            elif pattern_type in ["jmp", "loop"]:
                purposes.append("control flow")
            elif pattern_type in ["call", "function_definition"]:
                purposes.append("modularity and reusability")
        
        main_purpose = max(set(purposes), key=purposes.count) if purposes else "general computation"
        
        if user_level == "beginner":
            return f"This code is designed for {main_purpose}. It's the kind of code you'd find in programs that need to {main_purpose.replace('_', ' ')} efficiently."
        
        elif user_level == "intermediate":
            use_cases = {
                "data processing": "applications like databases, file processors, or data analysis tools",
                "decision making": "programs that need to make choices based on conditions, like games or business logic",
                "control flow": "systems that need precise execution control, like operating systems or embedded systems",
                "modularity": "large applications that break complex tasks into smaller, manageable pieces"
            }
            return f"This code serves {main_purpose} purposes. You'd typically find this in {use_cases.get(main_purpose, 'various software systems')}."
        
        elif user_level == "advanced":
            return f"This code implements {main_purpose} with performance optimization in mind. It's designed for systems where {main_purpose.replace('_', ' ')} efficiency is critical, such as high-performance computing, real-time systems, or performance-critical applications."
        
        else:  # expert
            return f"This code architecturally serves {main_purpose} requirements with consideration for scalability, maintainability, and performance characteristics. It demonstrates patterns commonly found in enterprise systems, performance-critical applications, or specialized computational domains."

    async def _answer_what_systems_use_it(self, code_snippet: str, user_level: str, language: str) -> str:
        """Answer 'What systems use this kind of code?' - explain real-world applications"""
        patterns = self._detect_assembly_patterns(code_snippet) if language == "assembly" else self._detect_highlevel_patterns(code_snippet, language)
        
        # Map patterns to system types
        system_types = set()
        for pattern in patterns:
            pattern_type = pattern["type"]
            if pattern_type in ["mov", "push", "pop"]:
                system_types.update(["operating systems", "embedded systems", "device drivers"])
            elif pattern_type in ["cmp", "jmp"]:
                system_types.update(["compilers", "interpreters", "game engines"])
            elif pattern_type in ["call", "function_definition"]:
                system_types.update(["web applications", "mobile apps", "enterprise software"])
            elif pattern_type in ["loop", "conditional"]:
                system_types.update(["data processing systems", "scientific computing", "AI/ML systems"])
        
        systems = list(system_types)[:4]  # Limit to top 4
        
        if user_level == "beginner":
            return f"You'll find this kind of code in {', '.join(systems[:2])} and many other computer programs. Most software uses similar patterns!"
        
        elif user_level == "intermediate":
            specific_examples = {
                "operating systems": "like Windows, Linux, or macOS",
                "web applications": "like Facebook, Google, or online banking",
                "game engines": "like Unity, Unreal Engine, or custom game code",
                "embedded systems": "like smart phones, cars, or IoT devices",
                "compilers": "like GCC, Clang, or language interpreters",
                "enterprise software": "like database systems, ERP software, or business applications"
            }
            
            examples = [f"{system} {specific_examples.get(system, '')}" for system in systems]
            return f"This code pattern is commonly used in: {', '.join(examples)}."
        
        elif user_level == "advanced":
            return f"This code architecture is employed in production systems including: {', '.join(systems)}. The specific optimization patterns suggest use in performance-critical contexts such as high-frequency trading, real-time systems, or large-scale distributed applications."
        
        else:  # expert
            return f"This implementation pattern is characteristic of enterprise-grade systems across domains: {', '.join(systems)}. The architectural choices indicate deployment in contexts requiring high reliability, performance, and maintainability - typical of mission-critical infrastructure, distributed computing platforms, or specialized domain applications."

    def _auto_detect_language(self, code_snippet: str) -> str:
        """Auto-detect programming language from code snippet"""
        code_lower = code_snippet.lower().strip()
        
        # Assembly indicators
        if any(keyword in code_lower for keyword in ["mov ", "cmp ", "jmp ", "push ", "pop ", "call "]):
            return "assembly"
        
        # Python indicators
        elif "def " in code_lower or "import " in code_lower or code_snippet.count(":") > code_snippet.count(";"):
            return "python"
        
        # JavaScript/TypeScript indicators
        elif "function " in code_lower or "const " in code_lower or "let " in code_lower or "var " in code_lower:
            return "javascript"
        
        # C++ indicators
        elif "#include" in code_lower or "std::" in code_lower or "cout" in code_lower:
            return "c++"
        
        # Rust indicators
        elif "fn " in code_lower or "let mut" in code_lower or "use " in code_lower and "::" in code_lower:
            return "rust"
        
        # Java indicators
        elif "public class" in code_lower or "System.out" in code_lower or "public static void main" in code_lower:
            return "java"
        
        # Default to assembly if uncertain
        else:
            return "assembly"

    def _detect_assembly_patterns(self, assembly_code: str) -> List[Dict[str, Any]]:
        """Detect patterns in assembly code"""
        patterns = []
        lines = assembly_code.strip().split('\n')
        
        for line in lines:
            line = line.strip().lower()
            for pattern_type, pattern_info in self.translation_patterns.items():
                if pattern_type in line or any(keyword in line for keyword in [pattern_type]):
                    patterns.append({
                        "type": pattern_type,
                        "line": line,
                        "translation_info": pattern_info
                    })
        
        return patterns

    async def _generate_human_readable_code(self, patterns: List[Dict[str, Any]], target_language: str, context: Dict[str, Any] = None) -> str:
        """Generate human-readable code from assembly patterns"""
        template = self.code_templates.get(target_language, self.code_templates["python"])
        
        # Build function context
        function_name = (context or {}).get("function_name", "assembly_optimized_function")
        parameters = (context or {}).get("parameters", "args")
        description = (context or {}).get("description", "Assembly-optimized function for maximum bot efficiency")
        
        # Start with file header and function signature
        code_lines = [
            template["file_header"],
            template["function_start"].format(
                function_name=function_name,
                parameters=parameters,
                description=description,
                assembly_notes="This function contains assembly-level optimizations"
            )
        ]
        
        # Add human-readable implementations of detected patterns
        for i, pattern in enumerate(patterns):
            pattern_type = pattern["type"]
            pattern_info = pattern["translation_info"]
            
            # Add assembly comment
            assembly_comment = template["assembly_comment"].format(
                operation=pattern_type.replace("_", " ").title(),
                assembly_code=pattern_info["assembly"]
            )
            code_lines.append(assembly_comment)
            
            # Add human-readable implementation
            if target_language == "python":
                implementation = pattern_info["python"]
            elif target_language in ["typescript", "javascript"]:
                implementation = pattern_info["typescript"]
            else:
                implementation = pattern_info["python"]  # fallback
            
            # Indent properly
            indented_implementation = "    " + implementation.replace("\n", "\n    ")
            code_lines.append(indented_implementation + "\n")
        
        # Add return statement
        if target_language == "python":
            code_lines.append("    return result  # Assembly-optimized return\n")
        elif target_language in ["typescript", "javascript"]:
            code_lines.append("    return result; // Assembly-optimized return\n")
            code_lines.append("}\n")
        
        return "".join(code_lines)

    def _calculate_readability_score(self, code: str, language: str) -> float:
        """Calculate readability score of generated code"""
        # Simple readability metrics
        lines = code.split('\n')
        comment_lines = len([l for l in lines if '//' in l or '#' in l])
        total_lines = len([l for l in lines if l.strip()])
        
        comment_ratio = comment_lines / max(total_lines, 1)
        
        # Base readability score
        base_score = 0.7
        
        # Bonus for good commenting
        comment_bonus = min(comment_ratio * 0.3, 0.2)
        
        # Language-specific adjustments
        language_bonus = {
            "python": 0.1,
            "typescript": 0.05,
            "javascript": 0.0,
            "rust": -0.05,
            "c++": -0.1
        }.get(language, 0)
        
        return min(base_score + comment_bonus + language_bonus, 1.0)

    def _estimate_performance_retention(self, patterns: List[Dict[str, Any]]) -> float:
        """Estimate how much assembly performance is retained"""
        if not patterns:
            return 0.8
        
        # Average efficiency of detected patterns
        efficiencies = []
        for pattern in patterns:
            # Mock efficiency based on pattern type
            efficiency_map = {
                "mov": 0.95,
                "jmp": 0.85, 
                "call": 0.80,
                "cmp": 0.90,
                "push": 0.85,
                "pop": 0.85,
                "loop": 0.90
            }
            efficiencies.append(efficiency_map.get(pattern["type"], 0.75))
        
        return sum(efficiencies) / len(efficiencies)

    async def create_human_readable_dmlog_components(self):
        """Create human-readable versions of DMLog components with assembly optimizations"""
        logger.info("🎨 Creating human-readable DMLog components with assembly optimizations...")
        
        components = [
            {
                "name": "dice_roller",
                "assembly": "mov eax, [rng_seed]\nmul ebx\nmod ecx",
                "context": {
                    "function_name": "roll_dice",
                    "parameters": "sides: int, count: int = 1",
                    "description": "Assembly-optimized dice rolling with hardware RNG"
                }
            },
            {
                "name": "character_sheet",
                "assembly": "mov eax, [character_stats]\nadd eax, [modifier]\nstore [result_addr]",
                "context": {
                    "function_name": "calculate_character_stats", 
                    "parameters": "base_stats: Dict, modifiers: Dict",
                    "description": "Assembly-optimized character stat calculation"
                }
            },
            {
                "name": "combat_engine",
                "assembly": "cmp eax, [ac_value]\njge hit_target\njmp miss_target",
                "context": {
                    "function_name": "resolve_attack",
                    "parameters": "attack_roll: int, armor_class: int, damage: int",
                    "description": "Assembly-optimized combat resolution engine"
                }
            }
        ]
        
        translations = []
        for component in components:
            # Translate to multiple languages for broader accessibility
            for language in ["python", "typescript"]:
                translation = await self.translate_assembly_to_human(
                    component["assembly"],
                    language,
                    component["context"]
                )
                translation["component_name"] = component["name"]
                translations.append(translation)
        
        logger.info(f"✅ Created {len(translations)} human-readable component translations")
        return translations

# FastAPI app setup
app = FastAPI(
    title="CodeBridge - Assembly-to-Human Translator",
    description="Translates assembly-optimized bot code to human-readable formats with detailed explanations",
    version="1.0.0"
)

# Global translator instance
translator = HumanReadableTranslator()

@app.get("/")
async def root():
    """Root endpoint"""
    return {
        "translator": translator.name,
        "specialization": translator.specialization,
        "supported_languages": translator.supported_languages,
        "status": "translating_assembly_to_human",
        "mission": "Bridge assembly-optimized bot code to human-readable formats"
    }

@app.post("/translate")
async def translate_code(request: dict):
    """Translate assembly code to human-readable format"""
    assembly_code = request.get("assembly_code", "")
    target_language = request.get("target_language", "python")
    context = request.get("context", {})
    
    if not assembly_code:
        raise HTTPException(status_code=400, detail="assembly_code is required")
    
    result = await translator.translate_assembly_to_human(assembly_code, target_language, context)
    return result

@app.post("/translate-with-preferences")
async def translate_with_preferences(request: dict):
    """Translate assembly code using developer's language preferences"""
    assembly_code = request.get("assembly_code", "")
    language_preferences = request.get("language_preferences", ["python", "c++", "rust"])
    context = request.get("context", {})
    
    if not assembly_code:
        raise HTTPException(status_code=400, detail="assembly_code is required")
    
    if not language_preferences or not isinstance(language_preferences, list):
        raise HTTPException(status_code=400, detail="language_preferences must be a non-empty list")
    
    result = await translator.translate_with_preferences(assembly_code, language_preferences, context)
    return result

@app.get("/dmlog-components")
async def get_dmlog_components():
    """Get human-readable DMLog components with assembly optimizations"""
    components = await translator.create_human_readable_dmlog_components()
    return {
        "total_components": len(components),
        "components": components,
        "optimization_notes": "All components retain assembly-level performance with human readability"
    }

@app.get("/translations")
async def get_translation_history():
    """Get translation history"""
    cursor = translator.conn.cursor()
    cursor.execute('SELECT * FROM translations ORDER BY timestamp DESC LIMIT 10')
    translations = cursor.fetchall()
    
    return {
        "recent_translations": len(translations),
        "translations": [
            {
                "target_language": t[2],
                "readability_score": f"{t[5]:.1%}",
                "performance_retention": f"{t[6]:.1%}",
                "timestamp": t[7]
            }
            for t in translations
        ]
    }

@app.get("/patterns")
async def get_supported_patterns():
    """Get supported assembly patterns"""
    return {
        "supported_patterns": list(translator.translation_patterns.keys()),
        "pattern_details": translator.translation_patterns
    }

@app.post("/explain-code")
async def explain_code_section(request: dict):
    """Interactive chatbot explains any selected code section"""
    code_snippet = request.get("code_snippet", "")
    user_level = request.get("user_level", "intermediate")
    language = request.get("language", "assembly")
    question_type = request.get("question_type", "general")  # general, what_does_it_do, what_for, what_systems_use_it
    
    if not code_snippet:
        raise HTTPException(status_code=400, detail="code_snippet is required")
    
    # Get comprehensive explanation
    explanation = await translator.explain_code_section(code_snippet, user_level, language)
    
    # Add question-specific information
    if question_type == "what_does_it_do":
        explanation["focused_answer"] = await translator._answer_what_does_it_do(code_snippet, user_level, language)
    elif question_type == "what_for":
        explanation["focused_answer"] = await translator._answer_what_is_it_for(code_snippet, user_level, language)
    elif question_type == "what_systems_use_it":
        explanation["focused_answer"] = await translator._answer_what_systems_use_it(code_snippet, user_level, language)
    
    return explanation

@app.post("/quick-explain")
async def quick_explain(request: dict):
    """Quick explanation for selected code - answers 'what does this do?'"""
    code_snippet = request.get("code_snippet", "")
    user_level = request.get("user_level", "intermediate")
    
    if not code_snippet:
        raise HTTPException(status_code=400, detail="code_snippet is required")
    
    # Auto-detect language
    language = translator._auto_detect_language(code_snippet)
    
    # Get focused explanation
    answer = await translator._answer_what_does_it_do(code_snippet, user_level, language)
    
    return {
        "code_snippet": code_snippet,
        "detected_language": language,
        "user_level": user_level,
        "quick_answer": answer,
        "response_type": "what_does_it_do"
    }

if __name__ == "__main__":
    import os
    
    logger.info("🚀 Starting CodeBridge - Assembly-to-Human Translator")
    logger.info("🌉 Mission: Bridge assembly-optimized code to human readability")
    logger.info("💻 Supporting ChainMind language with human-accessible output")
    
    port = int(os.environ.get("PORT", 8565))
    uvicorn.run(app, host="0.0.0.0", port=port)