apiVersion: v1
kind: Namespace
metadata:
  name: dmlog-staging
  labels:
    environment: staging
    project: dmlog
---
apiVersion: v1
kind: Namespace
metadata:
  name: dmlog-production
  labels:
    environment: production
    project: dmlog
---
apiVersion: v1
kind: Namespace
metadata:
  name: dmlog-monitoring
  labels:
    environment: shared
    project: dmlog
    purpose: monitoring