#!/bin/bash
# ActiveLog Multi-Domain Nginx Deployment Script
# Generated by Bot 7 for Phase 3 multi-domain routing

set -euo pipefail

# Configuration
EC2_HOST="${EC2_HOST:-ubuntu@34.223.235.20}"
EC2_KEY="${EC2_KEY:-~/.ssh/personallog_key}"
NGINX_CONFIG_LOCAL="/home/activeloguser/activelog/nginx/sites-available/multi-domain.conf"
NGINX_CONFIG_REMOTE="/etc/nginx/sites-available/multi-domain"
NGINX_ENABLED_REMOTE="/etc/nginx/sites-enabled/multi-domain"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging function
log() {
    local level="$1"
    shift
    local message="$*"
    
    case "$level" in
        "ERROR")   echo -e "${RED}[$level]${NC} $message" >&2 ;;
        "SUCCESS") echo -e "${GREEN}[$level]${NC} $message" ;;
        "WARN")    echo -e "${YELLOW}[$level]${NC} $message" ;;
        "INFO")    echo -e "${BLUE}[$level]${NC} $message" ;;
        *)         echo -e "[$level] $message" ;;
    esac
}

# Print usage information
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Deploy multi-domain nginx configuration to EC2"
    echo ""
    echo "Options:"
    echo "  --host HOST     EC2 host/IP address (default: ubuntu@34.223.235.20)"
    echo "  --key KEY_FILE  SSH private key file (default: ~/.ssh/personallog_key)"
    echo "  --dry-run       Show what would be done without executing"
    echo "  --help          Show this help message"
    echo ""
    echo "Environment Variables:"
    echo "  EC2_HOST        EC2 host/IP address"
    echo "  EC2_KEY         SSH private key file path"
    echo ""
}

# Parse command line arguments
DRY_RUN=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --host)
            EC2_HOST="$2"
            shift 2
            ;;
        --key)
            EC2_KEY="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help)
            usage
            exit 0
            ;;
        *)
            log "ERROR" "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Validate inputs
if [[ -z "$EC2_HOST" ]]; then
    log "ERROR" "EC2 host is required (use --host or set EC2_HOST environment variable)"
    exit 1
fi

if [[ -z "$EC2_KEY" ]]; then
    log "ERROR" "SSH key is required (use --key or set EC2_KEY environment variable)"
    exit 1
fi

if [[ ! -f "$EC2_KEY" ]]; then
    log "ERROR" "SSH key file not found: $EC2_KEY"
    exit 1
fi

if [[ ! -f "$NGINX_CONFIG_LOCAL" ]]; then
    log "ERROR" "Nginx config file not found: $NGINX_CONFIG_LOCAL"
    exit 1
fi

# Main deployment function
deploy_nginx_config() {
    log "INFO" "Starting nginx multi-domain configuration deployment"
    log "INFO" "Target: $EC2_HOST"
    log "INFO" "Config: $NGINX_CONFIG_LOCAL"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log "INFO" "[DRY RUN] Would deploy nginx configuration"
        log "INFO" "[DRY RUN] Would upload: $NGINX_CONFIG_LOCAL -> $NGINX_CONFIG_REMOTE"
        log "INFO" "[DRY RUN] Would enable site and reload nginx"
        return 0
    fi
    
    # Upload nginx configuration
    log "INFO" "Uploading nginx configuration..."
    scp -i "$EC2_KEY" -o StrictHostKeyChecking=no "$NGINX_CONFIG_LOCAL" "$EC2_HOST:~/multi-domain.conf"
    
    # Move config to nginx directory and enable it
    log "INFO" "Installing and enabling nginx configuration..."
    ssh -i "$EC2_KEY" -o StrictHostKeyChecking=no "$EC2_HOST" << 'EOF'
        # Move config to sites-available
        sudo mv ~/multi-domain.conf /etc/nginx/sites-available/multi-domain
        
        # Remove default site if it exists
        sudo rm -f /etc/nginx/sites-enabled/default
        
        # Enable multi-domain site
        sudo ln -sf /etc/nginx/sites-available/multi-domain /etc/nginx/sites-enabled/multi-domain
        
        # Test nginx configuration
        sudo nginx -t
        
        # Reload nginx
        sudo systemctl reload nginx
        
        # Show nginx status
        sudo systemctl status nginx --no-pager
EOF
    
    log "SUCCESS" "Nginx configuration deployed and activated"
}

# Test the configuration
test_configuration() {
    log "INFO" "Testing nginx configuration..."
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log "INFO" "[DRY RUN] Would test nginx configuration"
        return 0
    fi
    
    # Test nginx config syntax
    ssh -i "$EC2_KEY" -o StrictHostKeyChecking=no "$EC2_HOST" "sudo nginx -t"
    
    if [[ $? -eq 0 ]]; then
        log "SUCCESS" "Nginx configuration test passed"
    else
        log "ERROR" "Nginx configuration test failed"
        return 1
    fi
}

# Show deployment summary
show_deployment_info() {
    cat << EOF

🚀 MULTI-DOMAIN NGINX DEPLOYMENT COMPLETE!

📋 Configuration Summary:
┌─────────────────────────────────────────────────────────────┐
│ Domain Routing Configuration                                │
├─────────────────────────────────────────────────────────────┤
│ personallog.ai  →  127.0.0.1:8000  (PersonalLog backend)   │
│ fishinglog.ai   →  127.0.0.1:8001  (FishingLog backend)    │
│ dmlog.ai        →  127.0.0.1:8002  (DMLog backend)         │
└─────────────────────────────────────────────────────────────┘

🔒 SSL Configuration:
┌─────────────────────────────────────────────────────────────┐
│ Certificate: /etc/ssl/certs/nginx-selfsigned.crt           │
│ Private Key: /etc/ssl/private/nginx-selfsigned.key         │
│ Protocols:   TLSv1.2, TLSv1.3                              │
│ Redirects:   HTTP → HTTPS (all domains)                    │
└─────────────────────────────────────────────────────────────┘

🌐 DNS Configuration (Route53):
┌─────────────────────────────────────────────────────────────┐
│ personallog.ai  →  34.223.235.20  (A Record, TTL: 300)     │
│ fishinglog.ai   →  34.223.235.20  (A Record, TTL: 300)     │
│ dmlog.ai        →  34.223.235.20  (A Record, TTL: 300)     │
└─────────────────────────────────────────────────────────────┘

📊 Nameservers (Update at your registrar):
┌─────────────────────────────────────────────────────────────┐
│ personallog.ai:                                             │
│   ns-660.awsdns-18.net                                      │
│   ns-345.awsdns-43.com                                      │
│   ns-1087.awsdns-07.org                                     │
│   ns-1537.awsdns-00.co.uk                                   │
├─────────────────────────────────────────────────────────────┤
│ fishinglog.ai:                                              │
│   ns-130.awsdns-16.com                                      │
│   ns-1223.awsdns-24.org                                     │
│   ns-983.awsdns-58.net                                      │
│   ns-1781.awsdns-30.co.uk                                   │
├─────────────────────────────────────────────────────────────┤
│ dmlog.ai:                                                   │
│   ns-170.awsdns-21.com                                      │
│   ns-652.awsdns-17.net                                      │
│   ns-1056.awsdns-04.org                                     │
│   ns-1833.awsdns-37.co.uk                                   │
└─────────────────────────────────────────────────────────────┘

⚠️  IMPORTANT NEXT STEPS:
1. Update domain registrar with the nameservers listed above
2. Ensure backend services are running on their designated ports:
   - PersonalLog on port 8000
   - FishingLog on port 8001  
   - DMLog on port 8002
3. Wait for DNS propagation (can take up to 48 hours)
4. Test HTTPS access to all domains (browsers will warn about self-signed cert)

🔧 Management Commands:
   Check nginx status:  ssh -i '$EC2_KEY' '$EC2_HOST' 'sudo systemctl status nginx'
   Reload nginx:        ssh -i '$EC2_KEY' '$EC2_HOST' 'sudo systemctl reload nginx'
   Test config:         ssh -i '$EC2_KEY' '$EC2_HOST' 'sudo nginx -t'
   View logs:           ssh -i '$EC2_KEY' '$EC2_HOST' 'sudo tail -f /var/log/nginx/*.log'

🎉 Multi-domain routing is now active!
EOF
}

# Main execution
main() {
    deploy_nginx_config
    test_configuration
    show_deployment_info
}

# Run main function
main "$@"

log "SUCCESS" "Multi-domain nginx deployment completed!"