#!/bin/bash
# SUPERINSTANCE WORKER BOT OPTIMIZATION COMMANDS
# Generated by Foreman based on proven performance patterns

echo "=== BOT UNIVERSITY OPTIMIZATION BRIEFING ==="
echo "📚 Visit bot_university/ for latest optimization knowledge"
echo "🎯 SuperInstance Status: Infrastructure ✅, Services ✅, Domains 🟡"
echo "⚡ Key Efficiency: 95% token reduction via micro_updates.log format"
echo ""

echo "=== INFRASTRUCTURE BOT OPTIMIZATION ==="
echo "🔧 Your specialty: Deployment reliability, monitoring, scaling"
echo "📈 Performance pattern: ASSIST→START→COMPLETE in <6 minutes"
echo "🚀 Next focus: Advanced monitoring, auto-scaling, security hardening"
echo "📋 Command: Monitor services, optimize resource allocation, prepare next phase infrastructure"
echo ""

echo "=== SERVICES BOT OPTIMIZATION ==="  
echo "🔧 Your specialty: API development, authentication, database optimization"
echo "📈 Performance pattern: Consume pre-built resources immediately, no planning delay"
echo "🚀 Next focus: API endpoints, user workflows, performance optimization"
echo "📋 Command: Complete auth integration, build user management APIs, prepare domain service endpoints"
echo ""

echo "=== DOMAINS BOT OPTIMIZATION ==="
echo "🔧 Your specialty: Business logic, user experience, cross-domain analytics" 
echo "📈 Performance pattern: Ready schema + domain knowledge = rapid implementation"
echo "🚀 Next focus: ActiveLog fitness features, cross-domain correlations, user interface"
echo "📋 Command: Implement fitness tracking workflows, build analytics features, create user dashboards"
echo ""

echo "=== COORDINATION EFFICIENCY COMMANDS ==="
echo "# Update status efficiently (95% token reduction)"
echo 'echo "$(date +%H:%M)|your-bot|ACTION|task-description" >> /home/activeloguser/activelog/micro_updates.log'
echo ""
echo "# Check for collaboration opportunities"  
echo "python3 /home/activeloguser/activelog/dynamic_role_adaptation.py"
echo ""
echo "# Visit university before starting new phases"
echo "cat /home/activeloguser/activelog/bot_university/README.md"
echo ""
echo "# Monitor system resources"
echo "./resource_monitor.sh"
echo ""

echo "🎯 SUPERINSTANCE MISSION: Build cloud server superior to local server"
echo "🔥 PRIORITY DOMAIN: ActiveLog fitness tracking with cross-domain correlations"
echo "⚡ OPTIMIZATION GOAL: Apply bot_university knowledge for maximum velocity"