#!/usr/bin/env python3
"""
demo-fitness-app - Complete Fitness Application
Generated by SuperInstance One-Click Generator
"""

from fastapi import FastAPI, HTTPException, Depends, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, Field
from datetime import datetime, timedelta
from typing import Optional, List
import uvicorn
import jwt
import os

app = FastAPI(
    title="Demo Fitness App",
    description="Complete fitness tracking application with workouts, nutrition, and analytics",
    version="1.0.0"
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Security
security = HTTPBearer()
JWT_SECRET = os.getenv("JWT_SECRET", "fitness-app-secret-key")

# Models
class LoginRequest(BaseModel):
    username: str = Field(..., min_length=3, max_length=50)
    password: str = Field(..., min_length=6)

class TokenResponse(BaseModel):
    access_token: str
    token_type: str
    expires_in: int

class WorkoutCreate(BaseModel):
    workout_name: str = Field(..., min_length=1, max_length=200)
    workout_type: str = Field(..., min_length=1, max_length=100)
    duration_minutes: int = Field(..., ge=1, le=600)
    calories_burned: Optional[int] = Field(None, ge=0)
    notes: Optional[str] = Field(None, max_length=1000)

class NutritionEntry(BaseModel):
    food_item: str = Field(..., min_length=1, max_length=200)
    calories: int = Field(..., ge=0, le=10000)
    meal_type: str = Field("other", pattern="^(breakfast|lunch|dinner|snack|other)$")
    protein_g: Optional[float] = Field(None, ge=0)
    carbs_g: Optional[float] = Field(None, ge=0)
    fat_g: Optional[float] = Field(None, ge=0)

class BodyMeasurement(BaseModel):
    measurement_type: str = Field(..., min_length=1, max_length=50)
    value: float = Field(..., gt=0)
    unit: str = Field(..., min_length=1, max_length=20)
    notes: Optional[str] = Field(None, max_length=500)

def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.utcnow() + timedelta(hours=24)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, JWT_SECRET, algorithm="HS256")
    return encoded_jwt

def verify_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    try:
        payload = jwt.decode(credentials.credentials, JWT_SECRET, algorithms=["HS256"])
        username: str = payload.get("sub")
        if username is None:
            raise HTTPException(status_code=401, detail="Invalid token")
        return username
    except jwt.PyJWTError:
        raise HTTPException(status_code=401, detail="Invalid token")

# Auth endpoints
@app.post("/auth/login", response_model=TokenResponse)
async def login(request: LoginRequest):
    # Simple demo auth - replace with real authentication
    if request.username == "demo" and request.password == "password":
        access_token = create_access_token(data={"sub": request.username})
        return TokenResponse(
            access_token=access_token,
            token_type="bearer",
            expires_in=86400  # 24 hours
        )
    raise HTTPException(status_code=401, detail="Invalid credentials")

@app.get("/auth/validate")
async def validate_token(current_user: str = Depends(verify_token)):
    return {"valid": True, "user": current_user}

# Main endpoints
@app.get("/")
async def root():
    return {
        "app": "demo-fitness-app",
        "type": "fitness",
        "features": ["workouts", "nutrition", "measurements", "analytics", "auth"],
        "endpoints": {
            "auth": "/auth/login",
            "workouts": "/api/workouts",
            "nutrition": "/api/nutrition", 
            "measurements": "/api/measurements",
            "analytics": "/api/analytics"
        },
        "docs": "/docs"
    }

@app.get("/health")
async def health_check():
    return {
        "status": "healthy",
        "service": "demo-fitness-app",
        "type": "fitness",
        "timestamp": datetime.utcnow().isoformat()
    }

# Workout endpoints
@app.post("/api/workouts")
async def log_workout(workout: WorkoutCreate, current_user: str = Depends(verify_token)):
    # TODO: Save to database
    workout_data = workout.dict()
    workout_data["user"] = current_user
    workout_data["logged_at"] = datetime.utcnow().isoformat()
    return {"message": "Workout logged successfully", "workout": workout_data}

@app.get("/api/workouts")
async def get_workouts(current_user: str = Depends(verify_token)):
    # TODO: Retrieve from database
    return {"workouts": [], "user": current_user}

# Nutrition endpoints
@app.post("/api/nutrition")
async def log_nutrition(entry: NutritionEntry, current_user: str = Depends(verify_token)):
    # TODO: Save to database
    nutrition_data = entry.dict()
    nutrition_data["user"] = current_user
    nutrition_data["logged_at"] = datetime.utcnow().isoformat()
    return {"message": "Nutrition entry logged successfully", "entry": nutrition_data}

@app.get("/api/nutrition")
async def get_nutrition(days: int = 7, current_user: str = Depends(verify_token)):
    # TODO: Retrieve from database
    return {"nutrition_entries": [], "days": days, "user": current_user}

# Measurement endpoints
@app.post("/api/measurements")
async def record_measurement(measurement: BodyMeasurement, current_user: str = Depends(verify_token)):
    # TODO: Save to database
    measurement_data = measurement.dict()
    measurement_data["user"] = current_user
    measurement_data["recorded_at"] = datetime.utcnow().isoformat()
    return {"message": "Measurement recorded successfully", "measurement": measurement_data}

@app.get("/api/measurements")
async def get_measurements(measurement_type: Optional[str] = None, current_user: str = Depends(verify_token)):
    # TODO: Retrieve from database
    return {"measurements": [], "type": measurement_type, "user": current_user}

# Analytics endpoints
@app.get("/api/analytics/progress")
async def get_progress_analytics(days: int = 30, current_user: str = Depends(verify_token)):
    # TODO: Calculate from database
    return {
        "user": current_user,
        "period_days": days,
        "total_workouts": 0,
        "total_calories_burned": 0,
        "avg_workout_duration": 0,
        "nutrition_summary": {
            "avg_daily_calories": 0,
            "avg_protein": 0,
            "avg_carbs": 0,
            "avg_fat": 0
        },
        "measurements_trend": [],
        "achievements": []
    }

@app.get("/api/analytics/dashboard")
async def get_dashboard(current_user: str = Depends(verify_token)):
    return {
        "user": current_user,
        "today": datetime.utcnow().date().isoformat(),
        "quick_stats": {
            "workouts_this_week": 0,
            "calories_logged_today": 0,
            "last_measurement_date": None
        },
        "recent_activity": [],
        "goals_progress": []
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8501)
